[package]
name = "rusty-pipe"
version = "0.1.0"
authors = ["Coding Badly <bcook@rowdydog.com>"]
edition = "2018"

[dependencies]
ansi_term = "0"
args = "2.1"
base64 = "0.11"
caps = "0.3"
chrono = "0.4"
chrono = "0.4"
chrono = "0.4.10"
clap = "2.33"
futures = "0.1"
futures = "0.3"
futures-util = "0.3"
getopts = "0.2"
h2 = "0.2"
hex = "0.4"
http = "0.2"
hyper = "0.13"
hyper-rustls = "0.16"
lazy_static = "1.4"
lazy_static = "1.4.0"
libc = "0.2"
log = "0.3.8"
log = "0.4"
log4rs = "0.9"
mime = "0.3"
mockito = "0.22"
nix = "0.16"
nix = "0.6"
ntp = "0.5"
num_cpus = "1.12"
oid = "0.1"
os_info = "1.3"
os_type = "2.2"
picky = "4.6"
picky-asn1 = "0.2"
picky-asn1-der = "0.2"
pin-project = "0.4"
rand = "0.7"
rand_chacha = "0.2"
regex = "1.3"
reqwest = "0.10"
reqwest = "0.9"
ring = "0.14"
rpassword = "4.0"
rustc-serialize = "0.3"
semver = "0.9"
serde = "1.0"
serde_json = "1.0"
sha2 = "0.8"
signal-hook = "0.1"
structopt = "0.3"
strum = "0.15"
strum_macros = "0.15"
sysinfo = "0.10.5"
systemstat = "0.1"
time = "0.1"
tokio = "0.2"
toml = "0.5"
touch = "0"
untrusted = "0.6"
url = "1.7"
users = "0"
winapi = { version = "0.3", features = ["impl-default", "combaseapi", "consoleapi", "errhandlingapi", "handleapi", "knownfolders", "lmcons",  "minwinbase", "minwindef", "ntdef", "processthreadsapi", "securitybaseapi", "shlobj", "synchapi", "winbase", "wincon", "winerror", "winnt", "winsvc", "winuser", "winver", ] }
