name: "Test #2"
on:
  push:
    paths:
    - "Cargo.toml"
    - "**.rs"
    - ".github/workflows/test2.yml"
jobs:
  prepare_rust_image:
    name: "Build it"
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: "Install Rust"
      run: rustup update stable
    - name: Install cargo-wix
      run: cargo install cargo-wix
    - name: "Run the program"
      run: cargo +stable run
