
name: "Test #3 - Download"

on:
  push:
    paths:
    - ".github/workflows/test3.yml"

jobs:

  download_tests:

    name: "Download tests"

    runs-on: windows-latest

    steps:

    - name: "curl 1"
      run: curl --location --silent --output curl-vc_redist.x64.exe https://aka.ms/vs/16/release/vc_redist.x64.exe
      shell: bash

    - name: "PowerShell 1"
      run: Invoke-WebRequest "https://aka.ms/vs/16/release/vc_redist.x64.exe" -OutFile "ps-vc_redist.x64.exe"

    - name: "curl 2"
      run: curl --location --silent --output curl-cargo.7z https://github.com/Coding-Badly/rusty-pipe/releases/latest/download/cargo.7z
      shell: bash

    - name: "PowerShell 2"
      run: Invoke-WebRequest "https://github.com/Coding-Badly/rusty-pipe/releases/latest/download/cargo.7z" -OutFile "ps-cargo.7z"

    - name: "curl 3"
      run: curl --location --silent --output curl-rustup.7z https://github.com/Coding-Badly/rusty-pipe/releases/latest/download/rustup.7z
      shell: bash

    - name: "PowerShell 3"
      run: Invoke-WebRequest "https://github.com/Coding-Badly/rusty-pipe/releases/latest/download/rustup.7z" -OutFile "ps-rustup.7z"

    - name: "Directory listing"
      run: dir
