
name: "Test #5 - Build when a new tag is pushed"

on:
  push:
    paths:
    - "Cargo.toml"
    - "**.rs"
    - ".github/workflows/test5.yml"
#    tags:
#    - '*'

jobs:
  prepare_rust_image:
    name: "Prepare Rust image for Windows"
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: "Remove Rust documentation"
      run: rustup component remove rust-docs
    - name: "Install Rust"
      run: rustup update stable
    - name: Install cargo-wix
      run: cargo install cargo-wix
    - name: "Run the program"
      run: cargo +stable run
    - name: "Archive .cargo"
      run: 7z a -bt -t7z -m0=lzma2 -mx=9 -r cargo.7z "$Env:USERPROFILE/.cargo/*"
    - name: "Archive .rustup"
      run: 7z a -bt -t7z -m0=lzma2 -mx=9 -r rustup.7z "$Env:USERPROFILE/.rustup/*"
    - name: "Upload Rust .cargo image"
      uses: actions/upload-artifact@v1
      with:
        name: cargo
        path: cargo.7z
    - name: "Upload Rust .rustup image"
      uses: actions/upload-artifact@v1
      with:
        name: rustup
        path: rustup.7z

# This is a test.
