name: Test #1
on:
  push:
    paths:
    - "Cargo.toml"
    - "**.rs"
    - ".github/workflows/test1.yml"
jobs:
  prepare_rust_image:
    name: "Prepare Rust image for Windows"
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: "Echo HOME"
      run: echo "%HOME%"
      shell: cmd
    - name: "Remove Rust documentation"
      run: rustup component remove rust-docs
    - name: "Install Rust"
      run: rustup update stable
#    - name: "Remove Rust documentation"
#      run: rustup component remove rust-docs
#      continue-on-error: true
    - name: "Run the program"
      run: cargo +stable run
    - name: "Archive .cargo"
      run: 7z a -bt -t7z -m0=lzma2 -mx=9 -r cargo.7z "$Env:USERPROFILE/.cargo/*"
    - name: "Archive .rustup"
      run: 7z a -bt -t7z -m0=lzma2 -mx=9 -r rustup.7z "$Env:USERPROFILE/.rustup/*"
    - name: "Upload Rust .cargo image"
      uses: actions/upload-artifact@v1
      with:
        name: Rust .cargo image
        path: cargo.7z
    - name: "Upload Rust .rustup image"
      uses: actions/upload-artifact@v1
      with:
        name: Rust .rustup image
        path: rustup.7z
  timing_test:
    name: "Build using Rust images"
    needs: prepare_rust_image
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: "'Remove' Rust (it's presented as a <JUNCTION>)"
      run: |
        rmdir "%USERPROFILE%/.cargo"
        rmdir "%USERPROFILE%/.rustup"
      shell: cmd
    - name: "Download Rust .cargo image"
      uses: actions/download-artifact@v1
      with:
        name: Rust .cargo image
        path: %HOME%/cargo.7z
#    - name: Download Rust .rustup image
#      uses: actions/download-artifact@v1
#      with:
#        name: Rust .rustup image
#        path: rustup.7z

#set PATH=%PATH%;C:\Program Files\7-Zip
#mkdir "%WHATEVER%\.cargo"
#cd "%WHATEVER%\.cargo"
#7z x "C:\Users\brian\Downloads\cargo.7z"
