name: Test #1
on:
  push:
    paths:
    - "Cargo.toml"
    - "**.rs"
    - ".github/workflows/test1.yml"
jobs:
  simple_build:
    name: Simple build for Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
#    - name: Remove Rust documentation
#      run: rustup component remove rust-docs
    - name: Install Rust
      run: rustup update stable
#    - name: Remove Rust documentation
#      run: rustup component remove rust-docs
#      continue-on-error: true
    - name: Run the program
      run: cargo +stable run
    - name: Archive .cargo
      run: 7z a -bt -t7z -m0=lzma2 -mx=9 -r cargo.7z "$Env:USERPROFILE/.cargo/*"
    - name: Archive .rustup
      run: 7z a -bt -t7z -m0=lzma2 -mx=9 -r rustup.7z "$Env:USERPROFILE/.rustup/*"
